version: "3"

services:
  # -------------------------
  # HADOOP NAMENODE
  # -------------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=datanode1:9864 datanode2:9864 datanode3:9864
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "9870:9870" # HDFS NameNode UI
    networks:
      - hadoop

  # -------------------------
  # HADOOP DATANODES (3)
  # -------------------------
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
      - hadoop

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
      - hadoop

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    networks:
      - hadoop

# -------------------------
# SPARK MASTER
# -------------------------
  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    command: bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    ports:
      - "8085:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master port
    networks:
      - hadoop
    depends_on:
      - namenode
      - kafka
    volumes:
      - ./ivy2_cache:/home/spark/.ivy2/cache   # writable Ivy cache
      - ./spark_jobs:/opt/spark/work-dir      # your local scripts
      - ./ivy2_jars:/home/spark/.ivy2/jars
      - ./spark_checkpoints:/tmp/spark_checkpoint   # <-- add this line

# -------------------------
# SPARK WORKER 1
# -------------------------
  spark-worker-1:
    image: apache/spark:3.5.3
    container_name: spark-worker-1
    command: bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    ports:
      - "8086:8081"
    networks:
      - hadoop
    depends_on:
      - spark-master
    volumes:
      - ./ivy2_cache:/home/spark/.ivy2/cache

# -------------------------
# SPARK WORKER 2
# -------------------------
  spark-worker-2:
    image: apache/spark:3.5.3
    container_name: spark-worker-2
    command: bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    ports:
      - "8087:8081"
    networks:
      - hadoop
    depends_on:
      - spark-master
    volumes:
      - ./ivy2_cache:/home/spark/.ivy2/cache
  # -------------------------
  # KAFKA (KRaft Mode)
  # -------------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"   # host access
      - "9093:9093"   # controller port
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: L6b6p6ZTR9u5xWJH3h7Z2A
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - hadoop




networks:
  hadoop:

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  kafka_data:




